version: "2"

networks:
  app-tier:
    driver: bridge


services:
  mongodb:
    image: 'mvertes/alpine-mongo'
    ports:
      - '27017:27017'
    volumes:
      - './dbdata:/data/db'
    networks:
      - app-tier
  
  nuchain-node:
    image: 'anvie/nuchain:latest-alpine'
    ports:
      - '9933:9933'
      - '9944:9944'
      - '30333:30333'
    volumes:
      - '/tmp/nuchain-testnet:/data'
    command: 'nuchain --base-path=/data --rpc-cors="*" --chain=testnet --bootnodes=/ip4/119.81.4.212/tcp/30334/p2p/12D3KooWK6urQQdUbyzu12R89pdE1TkQgPx1FaMHFXhkxfh84wgy  --pruning=archive --rpc-external --ws-external --rpc-methods=Unsafe'


# volumes:
#   dbdata:
#     driver: local
