name: package-ui-cd

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/ui/**'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy packages/ui
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "packages/ui"
          target: "~/arascan/src/packages/ui"

      - name: build packages/ui
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "packages/ui"
          script: "cd /var/www/html && ls -l"